service: serverless-image-resizer

provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "*"
  environment:
    SOURCE_S3_BUCKET_NAME: ${env:SOURCE_S3_BUCKET_NAME}
    SOURCE_S3_PREFIX: ${env:SOURCE_S3_PREFIX}

functions:
  sign:
    handler: index.sign
    events:
      - http:
          path: sign
          method: post
          cors: true
      - http:
          path: sign
          method: get
          cors: true


plugins:
  - serverless-webpack
  - create-s3-bucket-redirect
  - serverless-offline

custom:
  webpack: webpack.config.js
  webpackIncludeModules: true

resources:
  Resources:
    SourceImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:SOURCE_S3_BUCKET_NAME}
        AccessControl: PublicRead